version: '2'
services:
  db:
    image: mysql:8.0.16
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
    - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: mine

  redis:
    image: redis:3-alpine

  server:
    build: .
    command: python ./manage.py runserver 0.0.0.0:8000
    depends_on:
    - db
    - redis
    ports:
    - 8000:8000
    environment:
      DATABASE_URL: mysql://root:123@db:3306/mine
