# Generated by Django 2.2 on 2019-04-26 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('field', django_mysql.models.JSONField(default=dict)),
                ('field_size', models.IntegerField(default=8)),
                ('rest_flags_count', models.IntegerField(default=10)),
                ('status', models.CharField(choices=[('created', 'Created'), ('in_progress', 'In progress'), ('win', 'Win'), ('lose', 'Lose')], default='created', max_length=15)),
                ('current_turn', models.CharField(choices=[('first', 'First'), ('second', 'Second')], default='first', max_length=10)),
                ('first_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('second_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
